title: Namitha V Acharya
logo: /assets/img/logo.png
description: Dedicated technology enthusiast with a passion for data science, machine learning, and software development.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
